services:
  mariadb:
    build: ./mariadb
    restart: always
    volumes:
      - ./minestore/mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=random
      - MYSQL_DATABASE=minestore
      - MYSQL_USER=minestore_user
      - MYSQL_PASSWORD=12345678
      - timezone=UTC
    ports:
      - 3306:3306
  backend:
    build: ./backend
    environment:
      - randomPasswordMYSQL=12345678
      - timezone=UTC
      - minestoreDomain=ms.chrommob.fun
      - minestorePath=/var/www/minestore
      - phpVersion=8.2
      - licenseKey=
    volumes:
      - ./minestore/site:/var/www/minestore
      - php-socket:/run/php
  frontend:
    build: ./frontend
    restart: always
    volumes:
      - ./minestore/site:/var/www/minestore
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 3000:3000
  nginx:
    build: ./nginx
    restart: always
    environment:
      - minestoreDomain=ms.chrommob.fun
      - minestorePath=/var/www/minestore
      - phpVersion=8.2
      - server_ip=127.0.0.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./minestore/site:/var/www/minestore
      - php-socket:/run/php
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  php-socket:
